dw:
  target: dev
  outputs:
    lint:
      type: duckdb
      path: ":memory:"
      schema: main
      threads: 4

    dev:
      type: snowflake
      account: JJAYKGF-CW51069
      user: airbyte_user
      role: airbyte_role
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      database: airbyte_database
      warehouse: airbyte_warehouse
      schema: eeh_dev
      threads: 12
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: JJAYKGF-CW51069
      user: airbyte_user
      role: airbyte_role
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      database: airbyte_database
      warehouse: airbyte_warehouse
      schema: eeh_prod
      threads: 12
      client_session_keep_alive: False